# Generated by Django 3.1.4 on 2020-12-20 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AskNakaznoy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='rating',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
