# Generated by Django 3.1.4 on 2020-12-27 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AskNakaznoy', '0002_tag_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='pizza.jpg', upload_to='avatar/%y/%m/%d', verbose_name='Аватар'),
        ),
    ]
