# Generated by Django 3.1.4 on 2020-12-29 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AskNakaznoy', '0004_auto_20201228_2347'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerlike',
            name='is_voted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='questionlike',
            name='is_voted',
            field=models.BooleanField(default=False),
        ),
    ]
