# Generated by Django 3.1.4 on 2020-12-29 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AskNakaznoy', '0005_auto_20201229_0150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answerlike',
            name='is_voted',
        ),
        migrations.RemoveField(
            model_name='questionlike',
            name='is_voted',
        ),
    ]
